### PR TITLE
Fixes #29217 - puppet-tftp should run on el8

### PR DESCRIPTION
**Pull request by wbclark**

### CODE REVIEW

**Comment by ekohl** [comment]
FYI: https://github.com/theforeman/puppet-tftp/pull/98

**Comment by wbclark** [comment]
@ekohl do you mean that https://github.com/theforeman/puppet-tftp/blob/4d119ee0f5e1873e78437e48d9b496745325aa90/data/RedHat.yaml#L2 should be changed to `true` for el8 or you prefer to leave it at the current setting?

**Comment by ekohl** [comment]
I think my PR is the right approach and only needs to be rebased and green tests. Will look at rebasing it.

**Comment by mmoll** [comment]
GH-98 got merged, so there should be nothing left...

**Comment by ekohl** [comment]
Guess I should have taken the `Fixes` in my PR. Doing so manually.

**Pull request closed without merging**
