### PR TITLE
Support Ubuntu 20.04

### PR DESCRIPTION
**Pull request by ekohl**
The major change here is that Ubuntu 20.04 moves the default root from /var/lib/tftpboot to /srv/tftp. That matches what Debian does. The data files are changed so that only Ubuntu 16.04 and 18.04 have overrides. This technically breaks versions in between, but those aren't supported.

### CODE REVIEW

**Comment by ekohl** [comment]
The problem is that Ubuntu 20.04 defaults to `/srv/tftp` (like Debian) but we don't set the root directory in `/etc/default/tftpd-hpa`. That means changing the root directory was never really supported on Debian.

**Comment by ekohl** [comment]
Oh, https://github.com/theforeman/puppet-tftp/pull/91 would fix that.

**Comment by ekohl** [comment]
I started https://github.com/theforeman/puppet-tftp/pull/115.

**Comment by ekohl** [comment]
Test failures are expected.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
