### PR TITLE
Convert params pattern to module data with Hiera 4

### PR DESCRIPTION
**Pull request by domcleal**
Can wait until the module's Puppet 3 tests are removed.

### CODE REVIEW

**Comment by ekohl** [comment]
I like this. Is this something we want to do for all our modules and does kafo already understand this?

**Comment by domcleal** [comment]
Sure, and it does (though this module isn't included by Kafo in foreman-installer so won't be directly affected.)

**Comment by domcleal** [comment]
Rebased now that Puppet 3 tests are disabled. Reverted back to Hiera 4, which is compatible with 4.5 and above rather than depending on 4.9 or higher, just for greater compatibility (since 4.9 is very new and bugs in Hiera 5 led to lower uptake.) This means a deprecation warning will be issued on 4.9 and above.

**Comment by domcleal** [comment]
> Maybe the main class should also use types?

For sure. I'll probably work on this soon under a separate PR.

**Comment by ekohl** [comment]
> For sure. I'll probably work on this soon under a separate PR.

That works.

**Comment by mmoll** [comment]
Looking good, just to be extra sure: "Hiera 4" means "Hiera 3" correct?

**Comment by domcleal** [comment]
> Looking good, just to be extra sure: "Hiera 4" means "Hiera 3" correct?

No, it does mean 4. It's the version of Hiera that's built into Puppet 4.3+, is known as "Puppet lookup", and that supports module and environment data.

PR rebased.

**Comment by mmoll** [comment]
I see... https://docs.puppet.com/puppet/4.9/hiera_intro.html#what-happened-to-hiera-4-to-puppet-lookup

**Comment by mmoll** [comment]
merged, thanks @domcleal!

**Pull request merged**
