### PR TITLE
[WIP] Add more configuration options

### PR DESCRIPTION
**Pull request by ekohl**
This is a WIP PR that takes https://github.com/theforeman/puppet-tftp/pull/91 and adds tests + some cleanups.

### CODE REVIEW

**Comment by mmoll** [comment]
@ekohl Needs a rebase ;)

**Comment by ekohl** [comment]
Rebased. Let's see if the tests pass :)

**Comment by ekohl** [comment]
Looks like it doesn't work no EL systems.

**Comment by ekohl** [comment]
Included in https://github.com/theforeman/puppet-tftp/pull/115

**Pull request closed without merging**
